### ISSUE TITLE
Paletas exceden los limites

### ISSUE THREAD

**Issue by augusticor** [IS-II/PONG#21]
Las paletas exceden los limites del **canvas** tanto superior e inferior, creo que sobrepasa hasta la mitad de la paleta, tanto de teclado como de mouse

**Comment by AF-Backup** [comment]
Si el mouse va mas rapido que la paleta, esta se queda en el camino. Revisar soluciones

**Comment by augusticor** [comment]
Sucede lo mismo con el teclado, sería otro issue para esos dos features.
