### ISSUE TITLE
Aumentar la velocidad de la pelota dependiendo de ancho

### ISSUE THREAD

**Issue by augusticor** [IS-II/PONG#22]
Se debe **aumentar** la _velocidad_ de la pelota según el ancho de la pantalla o del canvas mejor, ya que si es demasiado ancha sera muy fácil jugar con esa resolución

**Comment by AF-Backup** [comment]
No, relSize ya es la relacion del tamaño, si se quiere ajustar, se debe mover el acompañante de relSize, eran 2 y 1.
Lo que hizo fue subir los valores a 5 y a 2.5.

> relSize * width / (width * 0.2)
> relSize * width / (width / 5)
> relSize * 5

> relSize * width / (width * 0.4)
> relSize * width / (width * 2 / 5)
> relSize * 5 / 2

**Comment by augusticor** [comment]
Dejemos la velocidad como la soluciono, entonces, me parece que esta bien para distintos tipos de tamaño

`this.deltaX = relSize * 5;`
` this.deltaY = relSize * 2.5;`
